export const LANGUAGE_LOADING = 'LANGUAGE_LOADING';
export const GET_LANGUAGES = 'GET_LANGUAGES';
export const GET_LANGUAGE = 'GET_LANGUAGE';
export const GET_LANGUAGE_BY_TAGS = 'GET_LANGUAGE_BY_TAGS';
